#!/bin/bash
#find -type f -name "*.gif" -printf '%f \n' | rev | cut --complement -c 1-5 | rev | LC_ALL=C sort -f
for f in *.gif; do printf "%s\n" "${f%.gif}" ; done && for f in .*.gif; do printf "%s\n" "${f%.gif}" ; done
